Network2d:
  in_channels: 3
  out_channels: 2
  deep_supervision: False
  need_features: True
  features: [32, 64, 128, 256, 512]
  dropout_p: [0., 0., 0.3, 0.4, 0.5]
  num_conv_per_stage: [2, 2, 3, 3, 3]
  kernel_size: [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3]]
  pool_kernel_size: [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2]]
  normalization: batchnorm
  activate: leakyrelu

Network3d:
  in_channels: 3
  out_channels: 2
  deep_supervision: False
  need_features: True
  features: [32, 64, 128, 256, 512]
  dropout_p: [0., 0., 0.3, 0.4, 0.5]
  num_conv_per_stage: [2, 2, 3, 3, 3]
  kernel_size: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  pool_kernel_size: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  normalization: batchnorm
  activate: leakyrelu
